DROP TABLE IF EXISTS reservation;
DROP TABLE IF EXISTS workshop;
DROP TABLE IF EXISTS cook;
DROP TABLE IF EXISTS gourmet;
DROP TABLE IF EXISTS user_login;
DROP TABLE IF EXISTS user_account;
DROP TABLE IF EXISTS kitchen;
